### ISSUE TITLE
"i'm joining gatsby" blogpost has no webmentions

### ISSUE THREAD

**Issue by swyxio** [mxstbr/mxstbr.com#25]
just giving a heads up that it looks broken
![image](https://user-images.githubusercontent.com/6764957/74290289-69958700-4cff-11ea-9849-82c25ad5cf13.png)

i'm not sure what the cause is, everything looks ok

**Comment by mxstbr** [comment]
🤔 Great catch, thanks! Will investigate.

**Comment by mxstbr** [comment]
Yeah I can't figure out why. I added querying for blogposts without the trailing slash and it shows ~190 likes, but my tweet has ~2k likes 🤔 Very confused, I am not quite sure if the problem is on my side, on the brid.gy side or on the webmention.io side.

**Comment by sw-yx** [comment]
did you send brid.gy to recrawl the tweet? sometimes it takes a little while. 

i'm just chatting with them about backfill btw, in case u want to join in the convo. the world deserves to see your old posts :) https://github.com/snarfed/bridgy/issues/917

**Comment by mxstbr** [comment]
I have tried that a bunch of times now, that's why it went from 0 to 191 :confused: Hm.

**Comment by mxstbr** [comment]
![Screenshot 2020-03-25 at 09 40 20](https://user-images.githubusercontent.com/7525670/77517606-b6cb5380-6e7c-11ea-8808-33acaa31f3ee.png)

**Comment by mxstbr** [comment]
I have sort-of-ish fixed this by removing the webmention setup and storing the like count statically 😅 Better than looking broken...

**Comment by sw-yx** [comment]
haha ok. bridgy has been a little buggy for me too. might have to write my own (famous last words.. lol)
