### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/mxstbr.com#6]
I need to add an RSS feed, lots of people have requested one

**Comment by slpixe** [comment]
I was one of the people who emailed in requesting an RSS feed for following the blog. 👍 

I don't personally have notifications turned on for github repo releases.

Looks like your `pages/thoughts/index.js` fetches new posts with from script called `blog-posts`
you could potentially have `thoughts/feed/` with an index.js and have this return back either a xml or json response.

something like this might help: https://github.com/hongkiat/js-rss-reader/blob/master/rss.js

**Comment by slpixe** [comment]
Actually just realised its a bit more complex that originally thought.

as its using NextJS for the server, that page would also bring in the header/footer from `_app.js & _document.js`

which would mean having a custom `server.js` with a catch on requests to `/thoughts/feed`:
https://nextjs.org/docs/#custom-server-and-routing

**Comment by mxstbr** [comment]
I really want to avoid having a custom server, I want the site to be static.

Maybe I could have `rss.mxstbr.com` which is that custom express server and point to there? I could also path alias that to `mxstbr.com/feed.json` with Zeit's path alias feature.

What would that server look like?

**Comment by slpixe** [comment]
Yes I figured you might not want to swap out next server for a custom one which complicates the app/repo.

Doing it as a separate app/repo the server (either node or express) would probably need a script to scrape/parse the current `thoughts` page and map that the feed format.
This might need expanding in the future if the thoughts page was to have pagination etc.

**Comment by mxstbr** [comment]
It's probably good enough to `require('../../mxstbr.com/blog-posts')` since it's unlikely I'll ever develop that without this repo also cloned 😅

**Comment by slpixe** [comment]
That concept might work, didn't think you could import from other repos.
Also for that blog-posts script it's un-compiled and using imports so the
RSS app would need babel and to import it as well.

might be worth just using a external service like
http://fetchrss.com ? assuming the free-tier would work

**Comment by mxstbr** [comment]
Ended up just writing a small node script that adds a static feed.json to the root dir, this is live! https://mxstbr.com/feed.json

**Comment by michaelx** [comment]
https://mxstbr.com/feed.json 404’s for me. Any chance you’ll add it back?

**Comment by mxstbr** [comment]
Ah crap, I broke that when I switched to dynamic deployments due to mxstbr.com/ama. Will have to fix this, sorry about the troubles!

**Comment by pcr910303** [comment]
@mxstbr Pinging gently just in case you have forgot this!

**Comment by mxstbr** [comment]
I did forget this, thanks for the reminder @pcr910303! Unfortunately I don't have time to investigate this right now—if anybody has ideas how to generate a RSS feed with Next.js and dynamic deployments let me know or (even better) submit a PR :pray:
