### ISSUE TITLE
XML RSS Feed

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/mxstbr.com#7]
Maybe some feed readers do not support the JSON feed I built? Will have to wait for replies (https://mobile.twitter.com/mxstbr/status/1087292997480390656), but it might be worth building a XML version either way. 

Would have to adjust the `data/generate-json-feed.js` script to also generate a XML script.

**Comment by slpixe** [comment]
Noticed as well that I'm not sure feed readers can parse the datePublished at on the JSON feed as it's currently shorthand instead of RFC3339.

Might be able to replace the date in the JSON with `date.toISOString()`

**Comment by mxstbr** [comment]
PRs welcome!

**Comment by z0al** [comment]
I think I can look into this. Also, I'm curious why doesn't the current JSON Feed contain full text? Is it intentional?

```json
 {
      "id": "https://mxstbr.com/thoughts/css-in-js",
      "url": "https://mxstbr.com/thoughts/css-in-js",
      "title": "Why I Write CSS in JavaScript",
      "content_text": "For three years, I have styled my web apps without any `.css` files. Instead, I have written all the CSS in JavaScript. Let me explain. See https://mxstbr.com/thoughts/thoughts/css-in-js!",
      "summary": "For three years, I have styled my web apps without any `.css` files. Instead, I have written all the CSS in JavaScript. Let me explain.",
      "image": "/static/images/css-in-js.png",
      "date_published": "2019-02-18"
    }
```

**Comment by mxstbr** [comment]
That would be amazing!! :100:

----

Yes, I did not manage to convert the React components I have to plain text. Open to ideas on that front too!

**Comment by robinmetral** [comment]
I was just about to open an issue for this, you guys are great! :rocket: 

Here's how to check whether the generated feed is valid: https://validator.w3.org/feed/ (currently [it isn't](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmxstbr.com%2Ffeed.json%2F))

(side note, I'm reading feeds on my email client - [Thunderbird](https://support.mozilla.org/en-US/kb/how-subscribe-news-feeds-and-blogs) - which apparently doesn't yet support JSON)

**Comment by mxstbr** [comment]
Shipped: https://mxstbr.com/rss
